author: eccentric_nz
description:
  An assortment of useful tools for your server, including: explosion healer, ore announcer, solar furnace, /home command, /top command, /back command
main: me.eccentric_nz.bromleymassivetools.BromleyMassiveTools
name: BromleyMassiveTools
load: POSTWORLD
version: 1.2.1
api-version: '1.21'
website: http://tardisjenkins.duckdns.org:8080/job/bromleymassivetools
dev-url: http://tardisjenkins.duckdns.org:8080/job/bromleymassivetools
permissions:
  bromleymassivetools.use:
    description: Allow players to use BromleyMassiveTools commands.
    default: true
  solarfurnace.place:
    description: Give players the ability to create solar furnaces by placing a daylight dector on top of a furnace.
    default: op
  profession.change:
    description: Give players the ability to change villager professions.
    default: op
